#!/bin/sh
# 小米 R3D 路由模式首次启动配置

# 等待系统启动
sleep 3

# 检查是否已配置
if [ ! -f /etc/.router_mode_configured ]; then
    # 配置系统
    uci set system.@system[0].hostname='Xiaomi-R3D'
    uci set system.@system[0].timezone='CST-8'
    uci set system.@system[0].zonename='Asia/Shanghai'
    
    # 配置WAN口
    uci set network.wan=interface
    uci set network.wan.proto='dhcp'
    uci set network.wan.device='eth0'
    uci set network.wan.ipv6='auto'
    
    uci set network.wan6=interface
    uci set network.wan6.device='@wan'
    uci set network.wan6.proto='dhcpv6'
    
    # 配置LAN口
    uci set network.lan.proto='static'
    uci set network.lan.ipaddr='192.168.1.1'
    uci set network.lan.netmask='255.255.255.0'
    uci set network.lan.device='br-lan'
    
    # 启用DHCP
    uci set dhcp.lan.ignore='0'
    uci set dhcp.lan.start='100'
    uci set dhcp.lan.limit='150'
    uci set dhcp.lan.leasetime='12h'
    
    # 配置防火墙
    uci set firewall.@zone[1].masq='1'
    uci set firewall.@forwarding[0].src='lan'
    uci set firewall.@forwarding[0].dest='wan'
    
    # 配置无线
    if [ -f /etc/config/wireless ]; then
        uci set wireless.radio0.disabled='0'
        uci set wireless.radio1.disabled='0'
        uci set wireless.@wifi-iface[0].ssid='Xiaomi_R3D_5G'
        uci set wireless.@wifi-iface[0].encryption='psk2'
        uci set wireless.@wifi-iface[0].key='12345678'
        uci set wireless.@wifi-iface[1].ssid='Xiaomi_R3D_2.4G'
        uci set wireless.@wifi-iface[1].encryption='psk2'
        uci set wireless.@wifi-iface[1].key='12345678'
        uci commit wireless
    fi
    
    # 提交配置
    uci commit system
    uci commit network
    uci commit dhcp
    uci commit firewall
    
    # 清空root密码
    passwd -d root
    
    # 标记已配置
    touch /etc/.router_mode_configured
    
    # 重启服务
    /etc/init.d/system restart
    /etc/init.d/network restart
    /etc/init.d/firewall restart
    /etc/init.d/dnsmasq restart
fi
